name: nightly-update-history

on:
  schedule:
    # Runs daily at 06:00 UTC (≈ late afternoon/evening in Australia/Melbourne depending on DST)
    - cron: "0 6 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: nightly-update-history
  cancel-in-progress: false

jobs:
  update-history:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GP_Refactor
        uses: actions/checkout@v4
        with:
          ref: GP_Refactor

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install project (editable)
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Ensure directories exist
        run: |
          mkdir -p data models/v3.3 preds
          # ensure history file exists; create an empty CSV with header if not
          if [ ! -f data/NHL_HISTORY_UNION.csv ]; then
            echo "name,team,opponent,home_or_away,date,points" > data/NHL_HISTORY_UNION.csv
          fi

      - name: Run nightly update (merge FINAL results)
        env:
          SPORTSDATA_API_KEY: ${{ secrets.SPORTSDATA_API_KEY }}
        run: |
          python -m white_shorts.etl.update_history_from_api             --history_csv data/NHL_HISTORY_UNION.csv             --since_days 2             --key "${SPORTSDATA_API_KEY}"

      - name: Commit & push if history changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/NHL_HISTORY_UNION.csv
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            git commit -m "Nightly: update history ${TS} (UTC)"
            git push origin GP_Refactor
          fi
